version: "3.9"

services:

  postgres:
    image: postgres
    volumes:
      - ./psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build: ./
    image: z-cam:latest                        
    command: python manage.py runserver 0.0.0.0:9000
    volumes:                                        
      - ./:/code/
    ports:                                          
      - "9000:9000"                                 

